- name: Include distribution specific variables
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_facts.distribution }}-{{ ansible_facts.distribution_version }}.yml"
        - "{{ ansible_facts.os_family }}-{{ ansible_facts.distribution_major_version }}.yml"
        - "{{ ansible_facts.distribution }}.yml"
        - "{{ ansible_facts.os_family }}.yml"
        - default.yml
      paths:
        - "{{ role_path }}/vars"
  tags:
    - ansible_pull
    - ansible_pull_scheduler
    - packages
    - yum
    - apt

- include_tasks: "install/{{ ansible_facts.os_family }}.yml"
  tags:
    - ansible_pull
    - packages
    - yum
    - apt

- name: Set up user to run ansible-pull as
  include_tasks: user.yml
  tags:
    - ansible_pull
    - ansible_pull_user

- name: Create directory for Ansible repository
  file:
    dest: "{{ ansible_pull_workdir }}"
    state: directory
    owner: "{{ ansible_pull_user }}"
    group: "{{ ansible_pull_group }}"
    mode: '0700'
  tags:
    - ansible_pull

- name: Set up Python virtual environment with necessary packages
  include_tasks: venv.yml
  tags:
    - ansible_pull
    - packages
    - pip

- name: Set up SSH for access to the repository
  include_tasks: ssh.yml
  tags:
    - ansible_pull
    - ansible_pull_ssh

- name: Create configuration files
  include_tasks: config.yml
  tags:
    - ansible_pull

- name: Create job to periodiclly run ansible-pull
  include_tasks: job.yml
  tags:
    - ansible_pull

- name: Display SSH public key
  debug:
    msg: "Here is the public key that needs to be placed on the remote git server: {{ _ssh_key_generation.public_key }}"
  when: _ssh_key_generation is changed and ansible_pull_ssh_key_mgmt is not defined
  tags:
    - ansible_pull
    - ansible_pull_ssh
