- name: Include distribution specific variables
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_facts.distribution }}-{{ ansible_facts.distribution_version }}.yml"
        - "{{ ansible_facts.os_family }}-{{ ansible_facts.distribution_major_version }}.yml"
        - "{{ ansible_facts.distribution }}.yml"
        - "{{ ansible_facts.os_family }}.yml"
        - default.yml
      paths:
        - "{{ role_path }}/vars"
  tags:
    - ansible_pull
    - ansible_pull_scheduler
    - packages
    - yum
    - apt

- include_tasks: "install-{{ ansible_facts.os_family }}.yml"
  tags:
    - ansible_pull
    - packages
    - yum
    - apt

- name: Create directory for Ansible repository
  file:
    dest: "{{ ansible_pull_workdir }}"
    state: directory
    owner: root
    group: root
    mode: '0700'
  tags:
    - ansible_pull

- name: Upgrade pip inside virtual environment
  pip:
    name: pip
    state: latest
    virtualenv: /var/lib/ansible/.venv
  tags:
    - ansible_pull
    - packages
    - pip

- name: Install Python packages
  pip:
    name: "{{ item }}"
    state: latest
    virtualenv: /var/lib/ansible/.venv
  loop: "{{ ansible_pull_pip_packages }}"
  tags:
    - ansible_pull
    - packages
    - pip

- name: Copy logrotate settings
  template:
    src: ansible-logrotate.j2
    dest: /etc/logrotate.d/ansible-pull
    owner: root
    group: root
    mode: '0644'
  tags:
    - ansible_pull
    - ansible_pull_logrotate

- name: Copy ansible.cfg
  template:
    src: ansible.cfg.j2
    dest: /root/.ansible.cfg
    owner: root
    group: root
    mode: '0700'
  tags:
    - ansible_pull
    - ansible_pull_config

- name: Copy vault password file
  template:
    src: vault.j2
    dest: "{{ ansible_pull_vault_password_file }}"
    owner: root
    group: root
    mode: '0600'
  when: ansible_pull_vault_password is defined
  tags:
    - ansible_pull
    - ansible_pull_vault

- name: Generate SSH key for root
  user:
    name: root
    generate_ssh_key: true
  register: _ssh_key_generation
  when: ansible_pull_ssh_private_key is not defined
  tags:
    - ansible_pull
    - ansible_pull_ssh

- name: Create .ssh folder for root
  file:
    path: "/root/.ssh"
    state: directory
    owner: root
    group: root
    mode: '0700'
  when: ansible_pull_ssh_private_key is defined
  tags:
    - ansible_pull
    - ansible_pull_ssh

- name: Copy SSH private key for root
  template:
    src: id_rsa.j2
    dest: /root/.ssh/id_rsa
    owner: root
    group: root
    mode: '0600'
  when: ansible_pull_ssh_private_key is defined
  tags:
    - ansible_pull
    - ansible_pull_ssh

- name: Add host keys to known_hosts
  known_hosts:
    name: "{{ item.name }}"
    key: "{{ item.key }}"
    state: "{{ item.state }}"
  loop: "{{ ansible_pull_known_hosts | default([]) }}"
  tags:
    - ansible_pull
    - ansible_pull_ssh

- name: Start and enable {{ ansible_pull_scheduler }}
  service:
    name: "{{ ansible_pull_scheduler }}"
    enabled: yes
    state: started
  tags:
    - ansible_pull
    - ansible_pull_scheduler

- name: Create job to run ansible-pull
  cron:
    name: "{{ item.name }}"
    minute: "{{ item.minute }}"
    hour: "{{ item.hour }}"
    day: "{{ item.day }}"
    job: "{{ item.job }}"
    state: "{{ item.state }}"
    cron_file: "{{ item.cron_file | default(omit) }}"
    user: "{{ ansible_pull_user }}"
  loop: "{{ ansible_pull_cron_jobs }}"
  when: "'cron' in ansible_pull_scheduler"
  tags:
    - ansible_pull
    - ansible_pull_scheduler

- name: Display SSH public key
  debug:
    msg: "Here is the public key that needs to be placed on the remote git server: {{ _ssh_key_generation.ssh_public_key }}"
  when: _ssh_key_generation is changed and ansible_pull_ssh_key_mgmt is not defined
  tags:
    - ansible_pull
    - ansible_pull_ssh

- include_tasks: key_mgmt-{{ ansible_pull_ssh_key_mgmt }}.yml
  when: ansible_pull_ssh_key_mgmt is defined
  tags:
    - ansible_pull
    - ansible_pull_ssh
