- name: Use the python_virtualenv role to install Python packages in a virtual environment
  include_role:
    name: python_virtualenv
  vars:
    python_virtualenv_dir: "{{ ansible_pull_venv_dir }}"
    python_virtualenv_packages: "{{ ansible_pull_pip_packages }}"
    python_virtualenv_upgrade_pip: true
