- name: Convert cron to systemd time units
  set_fact:
    ansible_pull_cron_job: "{{ ansible_pull_cron_job | combine({ item: ansible_pull_cron_job[item] | regex_replace('\\*/', '0/') }) }}"
  loop:
    - hour
    - minute
    - day
  delegate_to: localhost
  tags:
    - ansible_pull
    - ansible_pull_scheduler
    - systemd

- name: Create systemd service unit file
  template:
    src: ansible-pull.service.j2
    dest: /etc/systemd/system/ansible-pull.service
  vars:
    job: "{{ ansible_pull_cron_job }}"
  notify: Reload systemd
  tags:
    - ansible_pull
    - ansible_pull_scheduler
    - systemd

- name: Create systemd timer unit file
  template:
    src: ansible-pull.timer.j2
    dest: /etc/systemd/system/ansible-pull.timer
  vars:
    job: "{{ ansible_pull_cron_job }}"
  notify: Reload systemd
  tags:
    - ansible_pull
    - ansible_pull_scheduler
    - systemd

- name: Start and enable the systemd timer
  systemd:
    name: ansible-pull.timer
    enabled: yes
    state: started
  tags:
    - ansible_pull
    - ansible_pull_scheduler
    - systemd

- name: Create systemd unit file for initial setup
  template:
    src: ansible-pull-initial.service.j2
    dest: /etc/systemd/system/ansible-pull-initial.service
  vars:
    job: "{{ ansible_pull_cron_job }}"
  notify: Reload systemd
  tags:
    - ansible_pull
    - ansible_pull_scheduler
    - systemd

- name: Enable the systemd service for initial setup
  systemd:
    name: ansible-pull-initial.service
    enabled: yes
  tags:
    - ansible_pull
    - ansible_pull_scheduler
    - systemd
